# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Import tank zpool from USB-C DAS
  boot.zfs.extraPools = [ "tank" ];
  boot.zfs.forceImportAll = true;  # Critical for external pools
  boot.zfs.devNodes = "/dev/disk/by-id";
  boot.postBootCommands = ''
    echo "=== STARTING ZPOOL IMPORT ==="
    ${pkgs.zfs}/bin/zpool import -a -N -d /dev/disk/by-id || true
    ${pkgs.zfs}/bin/zpool status
    ${pkgs.zfs}/bin/zfs mount -a
    echo "=== ZPOOL IMPORT COMPLETE ==="
  '';

  fileSystems."/" =
    { device = "zroot/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    # TODO: update disk uuid
    { device = "/dev/disk/by-uuid/8041-67D1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "zroot/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "zroot/safe/persist";
      fsType = "zfs";
    };

  swapDevices =
    # TODO: update disk uuid
    [ { device = "/dev/disk/by-uuid/59c09ea0-c438-4859-ac40-76d847fcfb5b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
